# Generated by Django 5.0.2 on 2025-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_plot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='map_address',
            field=models.CharField(blank=True, help_text='Full address for map (optional)', max_length=255, null=True),
        ),
    ]
