# Generated by Django 5.0.2 on 2025-12-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_profile_picture_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('none', 'No Plan'), ('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='none', max_length=10),
        ),
    ]
